/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	azurefunctionsv1 "github.com/yaron2/azfuncs/pkg/apis/azurefunctions/v1"
	versioned "github.com/yaron2/azfuncs/pkg/client/clientset/versioned"
	internalinterfaces "github.com/yaron2/azfuncs/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/yaron2/azfuncs/pkg/client/listers/azurefunctions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AzureFunctionInformer provides access to a shared informer and lister for
// AzureFunctions.
type AzureFunctionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AzureFunctionLister
}

type azureFunctionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAzureFunctionInformer constructs a new informer for AzureFunction type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAzureFunctionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAzureFunctionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAzureFunctionInformer constructs a new informer for AzureFunction type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAzureFunctionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DevV1().AzureFunctions(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DevV1().AzureFunctions(namespace).Watch(options)
			},
		},
		&azurefunctionsv1.AzureFunction{},
		resyncPeriod,
		indexers,
	)
}

func (f *azureFunctionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAzureFunctionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *azureFunctionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&azurefunctionsv1.AzureFunction{}, f.defaultInformer)
}

func (f *azureFunctionInformer) Lister() v1.AzureFunctionLister {
	return v1.NewAzureFunctionLister(f.Informer().GetIndexer())
}
