/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	azurefunctionsv1 "github.com/yaron2/azfuncs/pkg/apis/azurefunctions/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureFunctions implements AzureFunctionInterface
type FakeAzureFunctions struct {
	Fake *FakeDevV1
	ns   string
}

var azurefunctionsResource = schema.GroupVersionResource{Group: "dev.azure.com", Version: "v1", Resource: "azurefunctions"}

var azurefunctionsKind = schema.GroupVersionKind{Group: "dev.azure.com", Version: "v1", Kind: "AzureFunction"}

// Get takes name of the azureFunction, and returns the corresponding azureFunction object, and an error if there is any.
func (c *FakeAzureFunctions) Get(name string, options v1.GetOptions) (result *azurefunctionsv1.AzureFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azurefunctionsResource, c.ns, name), &azurefunctionsv1.AzureFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azurefunctionsv1.AzureFunction), err
}

// List takes label and field selectors, and returns the list of AzureFunctions that match those selectors.
func (c *FakeAzureFunctions) List(opts v1.ListOptions) (result *azurefunctionsv1.AzureFunctionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azurefunctionsResource, azurefunctionsKind, c.ns, opts), &azurefunctionsv1.AzureFunctionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &azurefunctionsv1.AzureFunctionList{ListMeta: obj.(*azurefunctionsv1.AzureFunctionList).ListMeta}
	for _, item := range obj.(*azurefunctionsv1.AzureFunctionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureFunctions.
func (c *FakeAzureFunctions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azurefunctionsResource, c.ns, opts))

}

// Create takes the representation of a azureFunction and creates it.  Returns the server's representation of the azureFunction, and an error, if there is any.
func (c *FakeAzureFunctions) Create(azureFunction *azurefunctionsv1.AzureFunction) (result *azurefunctionsv1.AzureFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azurefunctionsResource, c.ns, azureFunction), &azurefunctionsv1.AzureFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azurefunctionsv1.AzureFunction), err
}

// Update takes the representation of a azureFunction and updates it. Returns the server's representation of the azureFunction, and an error, if there is any.
func (c *FakeAzureFunctions) Update(azureFunction *azurefunctionsv1.AzureFunction) (result *azurefunctionsv1.AzureFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azurefunctionsResource, c.ns, azureFunction), &azurefunctionsv1.AzureFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azurefunctionsv1.AzureFunction), err
}

// Delete takes name of the azureFunction and deletes it. Returns an error if one occurs.
func (c *FakeAzureFunctions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azurefunctionsResource, c.ns, name), &azurefunctionsv1.AzureFunction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureFunctions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azurefunctionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &azurefunctionsv1.AzureFunctionList{})
	return err
}

// Patch applies the patch and returns the patched azureFunction.
func (c *FakeAzureFunctions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *azurefunctionsv1.AzureFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azurefunctionsResource, c.ns, name, data, subresources...), &azurefunctionsv1.AzureFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azurefunctionsv1.AzureFunction), err
}
